//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.QLTS.DEMO.Web04.PXTRUONG.Comon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QLTS.DEMO.Web04.PXTRUONG.Comon.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thêm  không thành công.
        /// </summary>
        public static string addFail {
            get {
                return ResourceManager.GetString("addFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thêm thành công.
        /// </summary>
        public static string addSuccess {
            get {
                return ResourceManager.GetString("addSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sử dụng không thể vượt quá ngày hiện tại .
        /// </summary>
        public static string checkDayUse {
            get {
                return ResourceManager.GetString("checkDayUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không vượt quá ngày hiện tại.
        /// </summary>
        public static string checkPurchaseDate {
            get {
                return ResourceManager.GetString("checkPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không thể sau ngày sử dụng .
        /// </summary>
        public static string checkPurchaseDayUse {
            get {
                return ResourceManager.GetString("checkPurchaseDayUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  đã  tồn tại.
        /// </summary>
        public static string codeExist {
            get {
                return ResourceManager.GetString("codeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chưa tồn tại.
        /// </summary>
        public static string codeUnExist {
            get {
                return ResourceManager.GetString("codeUnExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string delateSuccess {
            get {
                return ResourceManager.GetString("delateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập không đúng mã tài sản .
        /// </summary>
        public static string Dupplicate {
            get {
                return ResourceManager.GetString("Dupplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS00001.
        /// </summary>
        public static string FirstCode {
            get {
                return ResourceManager.GetString("FirstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thành công .
        /// </summary>
        public static string FixSuccess {
            get {
                return ResourceManager.GetString("FixSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vượt quá độ dài cho phép .
        /// </summary>
        public static string maxLength {
            get {
                return ResourceManager.GetString("maxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được bỏ trống .
        /// </summary>
        public static string notAllowNull {
            get {
                return ResourceManager.GetString("notAllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không tồn tại .
        /// </summary>
        public static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống .
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
    }
}
